apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: opentraum
  labels:
    app: auth-service
    app.kubernetes.io/part-of: opentraum
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
